### ISSUE TITLE
Effect crashing and becoming disabled in FCPx

### ISSUE THREAD

**Issue by richo1968** [latenitefilms/GyroflowToolbox#10]
Hey Team,
Awesome plug in for FCPx.  I have tried it out and it is working perfectly, I am however getting a crash when playing back the footage in the timeline.
It seems to work fine for a while but will crash randomly.  I have a Mac Studio with M1 Ultra and 64Gb Ram. OSX Monterey 12.6.2
and FCPx 10.6.5 and Gyroflow 1.4.2
I'm happy to do any testing that you need as I am shooting and editing lots of videos using DJI Avata and requiring Gyroflow.

When playing back the footage I do notice a short black screen in the viewer before it plays, seems to be doing something (assume loading gyro data for playback?).  Not sure if I should be pre rendering these files and/or making a compound clip.  I didn't get that far as it kept crashing.

Keep up the good work !

Also using BRAW plug in as I shoot with BMPCC 6K.  So far this is working great.

**Comment by latenitefilms** [comment]
Can you please share the crash report?

**Comment by latenitefilms** [comment]
You should be able to find any crash reports in:

**/Users/YOUR-USER-NAME/Library/Logs/DiagnosticReports**

**Comment by latenitefilms** [comment]
I haven't heard from you, so I'm going to close this issue for now. Please re-open it if you're still having issues.
