### ISSUE TITLE
Failed to launch Gyroflow.

### ISSUE THREAD

**Issue by shavethegoat** [latenitefilms/GyroflowToolbox#15]
Hi

I've just purchased the app but it doesn't work. 

It gives me the this message:

Failed to launch Gyroflow.
Please check that Gyroflow is installed in your Applications folder and try again.

What to do? 

Best regards
Anders

**Comment by latenitefilms** [comment]
Hi Anders,

I'm assuming you don't actually have Gyroflow installed?

Gyroflow is a completely seperate app from Gyroflow Toolbox.

You can download Gyroflow here:  https://gyroflow.xyz

Instructions here: https://gyroflowtoolbox.io/how-to-use/

Any questions let me know!

**Comment by mhbsavant** [comment]
I'm having the same issue, I've never got this app to work and I've owned it since March. I just made this account to see if I can find an answer. I purchased this from the app store along with the BRAW toolbox

**Comment by latenitefilms** [comment]
Have you also downloaded Gyroflow (which is separate to Gyroflow Toolbox)?

You can download for free here:

https://gyroflow.xyz
