### ISSUE TITLE
"Failed to launch Gyroflow." error message when launching from the Inspector in Final Cut 10.6.5

### ISSUE THREAD

**Issue by CharlesWrenFilms** [latenitefilms/GyroflowToolbox#16]
Howdy. 
We're getting an error dialogue when we click the "Launch Gyroflow" button in the Inspector.

The error message is titled "Failed to launch Gyroflow.", and it reads "Please check that Gyroflow is installed in your Applications folder and try again."

The Gyroflow Toolbox is in the Applications folder. 

Thanks in advance for any help.
<img width="328" alt="Gyroflow Error Message" src="https://user-images.githubusercontent.com/124067033/215796568-374e86ff-1ce5-4872-bd39-f566ae262b88.png">

**Comment by latenitefilms** [comment]
Howdy @CharlesWrenFilms !

Gyroflow is a completely seperate app from Gyroflow Toolbox.

You can download Gyroflow here: https://gyroflow.xyz/

Instructions here: https://gyroflowtoolbox.io/how-to-use/

Any questions let me know!

**Comment by CharlesWrenFilms** [comment]
Oh dear lord. Maybe I need some caffeine 😂Thanks for cleaning up the schoolboy error mate. Cheers!CharlesTHINK. CREATE. SHARE.Charles Wren | ***@***.***: 07940770657_____________________________Charles Wren Films is a trading name of THINK CREATE SHARE LTD | 109839167 Graphic House, Druid Street, Hinckley, Leics, LE10 1QHOn 31 Jan 2023, at 21:14, Chris Hocking ***@***.***> wrote:﻿
Howdy @CharlesWrenFilms !
Gyroflow is a completely seperate app from Gyroflow Toolbox.
You can download Gyroflow here: https://gyroflow.xyz/
Instructions here: https://gyroflowtoolbox.io/how-to-use/
Any questions let me know!
