### ISSUE TITLE
Bad BRAW stabilisation

### ISSUE THREAD

**Issue by Mcrubens** [latenitefilms/GyroflowToolbox#17]
BRAW stabilisation in Gyroflow itself is perfect. However, after loading the project in Final Cut Pro (in combo with the BRAW Toolbox), the clip is not perfectly stabilised. It is not completely rubbish, but certain fragments show really bad stabilisation. Is the Gyroflow toolbox compatible with the latest version of Gyroflow? 

I loaded the Gyroflow file with processed gyro data as this is the only file that worked with GyroflowToolbox. I did not clip the BRAW file.

**Comment by Mcrubens** [comment]
Some proof (to download): 
Gyroflow file = https://ln5.sync.com/dl/6f7a35420/f3h8w99h-y8gm7uts-dy96bprs-q4vpw8bx
Final Cut Pro = https://ln5.sync.com/dl/5de004920/8nqp638g-rzk5naru-yzq5jumj-r7h86fta

**Comment by Mcrubens** [comment]
And the Gyroflow project file: https://ln5.sync.com/dl/458b63540/85r38h4m-xdudh9gj-wavnubn9-2yivstba

**Comment by latenitefilms** [comment]
My sincerest apologies for the delayed reply - there seems to be some issues with GitHub emailing me post notifications, and I only just saw this. Sorry!

Gyroflow Toolbox actually uses the exact same "render engine" as the main Gyroflow app, so, in theory at least, you should get identical results. I can't tell from the videos - does your FOV, Smoothness and Lens Correction match between FCPX and Gyroflow?

All Gyroflow Toolbox does is essentially take the image from FCPX and sends it to Gyroflow for processing, then returns it back to Final Cut Pro. Gyroflow Toolbox doesn't actually do any of the image manipulation - it's all done by Gyroflow.

I've been working on a new version of Gyroflow Toolbox - which is still very much a work-in-progress - however feel free to give it a go via TestFlight and see if you're getting the same issues?

https://testflight.apple.com/join/nPBZO2aZ

**Comment by latenitefilms** [comment]
This issue might be a bug within `gyroflow_core` that's been addressed here:

https://github.com/gyroflow/gyroflow-ofx/issues/31

**Comment by latenitefilms** [comment]
This will be addressed in Gyroflow Toolbox v1.1.0.
