### ISSUE TITLE
Custom View buttons get cropped when Inspector is Small

### ISSUE THREAD

**Issue by JW144754** [latenitefilms/GyroflowToolbox#2]
Honoured to be on elf the first person who is beta testing this amazing plugin!

Initial installed on M1Max MacBook without any problem, playback was as smooth as any other effects.

First GUI bug would be when resizing the inspector window to smaller than the buttons, the buttons gets cut out from the left. See attached screenshot.

![GyroflowTB GUI](https://user-images.githubusercontent.com/72329359/208811224-11cf11ba-3e6c-4dea-a73d-bb03cbe7f3fd.png)

**Comment by latenitefilms** [comment]
Unfortunately this is a bug/limitation of Apple's FxPlug4 API. I've talked to the Final Cut Pro about this, and they haven't been able to offer a fix or workaround yet.

**Comment by JW144754** [comment]
Ah that is very unfortunate. Not a deal breaker at all though, I can absolutely live with it!

**Comment by latenitefilms** [comment]
As a workaround, I've just renamed them to "Export Project" and "Reload Project". This will be fixed in 1.0.0-beta.2.
