### ISSUE TITLE
Final cut plugin won't appear properly

### ISSUE THREAD

**Issue by Torahda** [latenitefilms/GyroflowToolbox#25]
Hi Chris, since the last Final Cut update, I can't use the plugin within the editing program anymore. The plugin window is no longer fully displayed and can't be scrolled. Do you have any idea how to fix this?

<img width="1193" alt="Bildschirmfoto 2023-08-18 um 12 38 04" src="https://github.com/latenitefilms/GyroflowToolbox/assets/140724495/ba7858ab-4378-4525-8ce9-100e0ff93037">

**Comment by latenitefilms** [comment]
It looks like you don't have the latest Motion Template installed.

Run the main Gyroflow Toolbox application again and make sure you install the Motion Template.

See: https://brawtoolbox.io/installation/

**Comment by Torahda** [comment]
Hi Chris,

thanks for your fast reply, it worked! :)
