### ISSUE TITLE
Source code build and install

### ISSUE THREAD

**Issue by kltdwrds** [latenitefilms/GyroflowToolbox#27]
I have built from source both the rust framework `.dylib` and FxPlug.  I moved `Gyroflow Toolbox.app` to my Applications folder and opened it.  That launches the native app and performs motion template installation.  I now have the Gyroflow effect inside of FCP effects explorer, but it's giving the red error view when applied to any clip.  

I believe the renderer `.pluginkit` found in developer build directory needs installed somewhere...?  I've not done FxPlug development before, guidance appreciated! 

Thanks for this awesome project.

**Comment by latenitefilms** [comment]
Did you code sign it?

Does it appear in Apple Motion? You might need to make your own Motion Template.

**Comment by kltdwrds** [comment]
> Did you code sign it?
i did, signing was probably the hardest part of getting the build to work 😄 

> Does it appear in Apple Motion? You might need to make your own Motion Template.
The app installed .moef to my `Motion Templates` folder

<img width="265" alt="Screenshot 2024-01-25 at 9 54 09 PM" src="https://github.com/latenitefilms/GyroflowToolbox/assets/5615037/30bef8bf-7474-4786-9120-130a1e287d9f">

But when i try clicking "open in motion" on the effect in FCP, I get the following error, which does seems consistent with how the effect is behaving in FCP...
<img width="705" alt="Screenshot 2024-01-25 at 9 55 31 PM" src="https://github.com/latenitefilms/GyroflowToolbox/assets/5615037/a5a35a7d-a45e-4ee7-9f12-770db6a4152c">

**Comment by kltdwrds** [comment]
> I believe the renderer `.pluginkit` found in developer build directory needs installed somewhere...?

What actions does an AppStore install perform other than copying `Gyroflow Toolbox.app` to `/Applications`?

My un-educated guess is i need to manually install `Gyroflow Toolbox Renderer.pluginkit` from the dev build output folder to where ever FCP / Motion looks for "filters or generators"...

<img width="730" alt="Screenshot 2024-01-25 at 10 01 47 PM" src="https://github.com/latenitefilms/GyroflowToolbox/assets/5615037/77a83f96-9ac0-4fdb-9324-d42482e68f85">

**Comment by latenitefilms** [comment]
No, all you need to do is run "Gyroflow Toolbox" from the Applications folder, and macOS will detect the plugin and allow Motion to access it. No need to move any files around.

Did you notarise the plugin? If you click "Product > Archive" you should be able to build for direct distribution (as opposed to App Store or TestFlight).

I think you'll need an Apple Developer Account for this all to work.

**Comment by latenitefilms** [comment]
In theory, you should just need to update the **Signing Team** here:

<img width="1126" alt="image" src="https://github.com/latenitefilms/GyroflowToolbox/assets/22286696/79f6f66c-b464-4779-969a-3fce870a0121">

...and here:

<img width="831" alt="image" src="https://github.com/latenitefilms/GyroflowToolbox/assets/22286696/0ac99be9-b5eb-4f8d-8e69-60cf887cd734">

...and here:

<img width="855" alt="image" src="https://github.com/latenitefilms/GyroflowToolbox/assets/22286696/139aff33-4d07-4e43-b67f-b5ca45e9fef4">

Then click **Product > Archive**:

<img width="327" alt="image" src="https://github.com/latenitefilms/GyroflowToolbox/assets/22286696/d013e42a-d142-4e5f-8ec2-6186296185a2">

Then click **Distribute App**:

<img width="1224" alt="image" src="https://github.com/latenitefilms/GyroflowToolbox/assets/22286696/b7dd6e0a-6549-4163-bfdd-ad95b4b3a0ac">

Then click **Direct Distribution**:

<img width="1440" alt="image" src="https://github.com/latenitefilms/GyroflowToolbox/assets/22286696/f6225307-a5e3-47cf-8455-59d39c10cf8f">

Once it's signed and notarised you can export the **Gyroflow Toolbox.app**, then simply move the Application to your Applications folder, open it, and away you go.

**Comment by latenitefilms** [comment]
I'll close for now, but yell out if you have any further issues/questions!
