### ISSUE TITLE
After importing Gyro Project, viewer not showing clip properly

### ISSUE THREAD

**Issue by JW144754** [latenitefilms/GyroflowToolbox#3]
After creating and importing the .gyroflow file, the stabilization looks correct, but the clip's height is reduced? See attached screen record. No other effect in use, 4k60p XAVC-HS footage from a a7siii in a 1080p30 timeline.

Viewer blurred out on purpose. Let me know if there is any further information I could provide to troubleshoot this!

https://user-images.githubusercontent.com/72329359/208811956-7e08e41e-408d-412f-ae03-9613c5ac92dd.mov

**Comment by latenitefilms** [comment]
Does it look correct in Gyroflow?

Did you save the Gyroflow File with processed gyro data?

<img width="279" alt="image" src="https://user-images.githubusercontent.com/22286696/208814410-9ff138e6-7844-44f8-8f81-b6cf43b5789e.png">

If you change Final Cut Pro's background to checkerboard, is the black area actually transparent?

<img width="665" alt="image" src="https://user-images.githubusercontent.com/22286696/208814779-e7680332-4b7e-430b-a804-52e7cc681a31.png">

**Comment by JW144754** [comment]
My bad, I totally did not save the "Processed gyro data" properly. It is working now. Looks good in Gyroflow, and looks the same in FCP. just the playback frame rate is much worse in FCP, but not complaining at all. Totally workable.

**Comment by latenitefilms** [comment]
Great news! When I get a chance I'll add some documentation and maybe also some kind of error message if you try to import a Gyroflow Project without any processed gyro data.

The playback performance in Gyroflow will definitely be much better than in Final Cut Pro currently, as it's heavily optimised and the developers spend a lot of love, care and attention to make it as performant as possible. Currently there's no way for us to send images from Final Cut Pro to Gyroflow and back again using ONLY Metal on the GPU - so there's a bit of a performance hit as we copy things from GPU to RAM to GPU again. Hopefully this is something that the Gyroflow team can improve on in the future - I know it's on their roadmap. Once this is done in `gyroflow_core` it should hopefully be pretty easy to update Gyroflow Toolbox to take advantage of it.

I'm going to close this issue for now, but feel free to re-open it if needed.
