### ISSUE TITLE
Gyroflow App smooth, Final Cut choppy

### ISSUE THREAD

**Issue by holzerna** [latenitefilms/GyroflowToolbox#30]
I stabilized a clip in the Gyroflow app. I get a smooth result.
Then I import the project on the clip in Final Cut (full length of the clip inside a compound clip).
When I play it back in Final Cut it is completely unusable. Choppy / jittery.
I know its "the same engine" but the result is not even close.
Am I missing something?

**Comment by latenitefilms** [comment]
My guess is that the Compound Clip frame rate is not identical to the clip frame rate?

**Comment by holzerna** [comment]
Thanks for your hint.
That's true. The original clip is 59.94fps and the compound clip is 23.98fps.
BUT

- The fps of the compound clip _cannot be changed._
- In addition to that, when I enter the compound clip and "I am now inside the compound clip" the jitter issue is the same even though the compound clip has no effect on the original clip in this view.

If it really is a question of fps missmatch, then how do you stabilize 60fps footage and use it on a 24fps timeline? This is the most normal use case I can think of.

**Comment by latenitefilms** [comment]
You'll need to create a new Compound Clip and make sure the frame size and frame rate is identical to the source clip.

**Comment by holzerna** [comment]
You can only change settings of a compound clip after you created it. Frame rate cannot be change at all.

**Comment by latenitefilms** [comment]
You can absolutely set the Compound Clip Settings on creation.

Right-click on your clip in the Browser and select **New Compound Clip..." (or press **OPTION+G**).

<img width="568" alt="image" src="https://github.com/latenitefilms/GyroflowToolbox/assets/22286696/e5cd257d-103f-4b39-ac40-394828aabdc4">

Sometimes Final Cut Pro will incorrectly "guess" the settings (which is most likely happening in your case), so click the **Use Custom Settings** button:

<img width="723" alt="image" src="https://github.com/latenitefilms/GyroflowToolbox/assets/22286696/8509bb94-2297-4761-8a0f-6eac535dbb18">

You can now make sure your Compound Clip matches your source clip settings:

<img width="723" alt="image" src="https://github.com/latenitefilms/GyroflowToolbox/assets/22286696/2b37ef2c-4f98-416b-9bdc-68cf7e6e1d05">

Most of the time Final Cut Pro guesses things right, if it's a "standard format" (i.e. it guessed it correctly in the above example for 59.94p footage), but if it's a non-standard format, it sometimes makes very poor guesses.

Hope this solves your issue!

**Comment by holzerna** [comment]
OK, I created the Compound Clip by selecting the original clip on the timeline and thus I didn't get the button for custom settings. You obviously have to select in in the file browser to have that option.
Thanks for the hint!
It seems that it only works in the timeline if the Compound Clip is at 40% speed. Which in this case is fine.
Thanks for taking the time to make the screen shots!
