### ISSUE TITLE
Gyroflow toolbox won't appear in effects browser after installation

### ISSUE THREAD

**Issue by BryanHuang66** [latenitefilms/GyroflowToolbox#34]
I have installed the motion template, but the gyroflow toolbox does not appear.

System:  15.0
FCPX: 10.8.1

<img width="784" alt="截屏2024-10-03 08 48 58" src="https://github.com/user-attachments/assets/d05b0d9e-a7b1-4e31-a3fd-63337e8cc3df">

**Comment by rgaufman** [comment]
What was the solution? - I'm experiencing the same here: https://github.com/latenitefilms/GyroflowToolbox/issues/35 - on MacOS 15.1

**Comment by BryanHuang66** [comment]
I found that the wrong folder permission was given. When I clicked the install motion templates button, the default folder did not seem to be the “movies” folder.
