### ISSUE TITLE
Installed but not seeing Gyroflow Toolbox in Final Cut

### ISSUE THREAD

**Issue by rgaufman** [latenitefilms/GyroflowToolbox#35]
I've purchased and installed the app, gave permission to the "Movies" folder:

![Screenshot 2024-10-10 at 18 33 09](https://github.com/user-attachments/assets/03702356-f855-45b6-b4f8-6a3d61577c30)

However I don't see anything new in my effects folder:

![Screenshot 2024-10-10 at 18 34 17](https://github.com/user-attachments/assets/31e74fb1-7fc6-43f2-ba65-c6b74e015107)

And I'm not seeing Gyroflow Toolbox:

![Screenshot 2024-10-10 at 18 33 43](https://github.com/user-attachments/assets/ad20a86e-87af-48ac-8aab-fbc3702697df)

My final cut version is 10.8.1:

![Screenshot 2024-10-10 at 18 33 48](https://github.com/user-attachments/assets/9cff979f-444e-4ec2-a7fc-50d847c6432b)

Any ideas please?

**Comment by latenitefilms** [comment]
Very strange. You can try just right-clicking on the `Gyroflow Toolbox.app`, and **Reveal Package Contents** and inside you'll find the Motion Template:

<img width="924" alt="image" src="https://github.com/user-attachments/assets/12437a55-3eac-470a-a7bb-7679a4656bea">

**Comment by latenitefilms** [comment]
Note to self - this might be the same issue on macOS 15 as in BRAW Toolbox:

https://github.com/latenitefilms/BRAWToolbox/issues/187

**Comment by latenitefilms** [comment]
This should be fixed in `v1.2.0`.
