### ISSUE TITLE
Only take effect after rendering

### ISSUE THREAD

**Issue by BryanHuang66** [latenitefilms/GyroflowToolbox#36]
After updating to version 1.2.0, I found that I need to render the timeline before I can see the stabilization effect. But there is no need to perform rendering operations in version 1.1.0.

**Comment by BryanHuang66** [comment]
If possible could you please give me the previous version of gyroflow toolbox(My computer is quite old and I really need this feature), my email is convergence99@outlook.com, many thanks

**Comment by BryanHuang66** [comment]
I use proxy media, which has no Better Quality/Better Performance options.
Sorry, I don't use Time Machine, and I would be very grateful if you could give me an older version dmg.

**Comment by latenitefilms** [comment]
My sincerest apologies for the lack of contact - it's been an insanely busy period.

Unfortunately we don't keep copies of old builds, as they're distributed through the Mac App Store, so each build is uniquely identified to each user (i.e. if we send you one of our copies, it would be tied to our Apple ID).
